// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtk3ol8FwqeD3rMgVT9vDhHlkqo04beZw',
    appId: '1:853733959938:web:c333d53d53583c3f1cba1b',
    messagingSenderId: '853733959938',
    projectId: 'zauto-driver-20e6b',
    authDomain: 'zauto-driver-20e6b.firebaseapp.com',
    storageBucket: 'zauto-driver-20e6b.firebasestorage.app',
    measurementId: 'G-2WNJPN3VJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCurqf8_QITIYlpNGM8eANLt2ZFpgXljYY',
    appId: '1:853733959938:android:82b91d6ade08732c1cba1b',
    messagingSenderId: '853733959938',
    projectId: 'zauto-driver-20e6b',
    storageBucket: 'zauto-driver-20e6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx_MSG7mB8950mqKhRSEC_HB-WpfRHxus',
    appId: '1:853733959938:ios:b4d7717794c625261cba1b',
    messagingSenderId: '853733959938',
    projectId: 'zauto-driver-20e6b',
    storageBucket: 'zauto-driver-20e6b.firebasestorage.app',
    iosBundleId: 'com.example.zautoDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx_MSG7mB8950mqKhRSEC_HB-WpfRHxus',
    appId: '1:853733959938:ios:b4d7717794c625261cba1b',
    messagingSenderId: '853733959938',
    projectId: 'zauto-driver-20e6b',
    storageBucket: 'zauto-driver-20e6b.firebasestorage.app',
    iosBundleId: 'com.example.zautoDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtk3ol8FwqeD3rMgVT9vDhHlkqo04beZw',
    appId: '1:853733959938:web:10dee193ccbb65491cba1b',
    messagingSenderId: '853733959938',
    projectId: 'zauto-driver-20e6b',
    authDomain: 'zauto-driver-20e6b.firebaseapp.com',
    storageBucket: 'zauto-driver-20e6b.firebasestorage.app',
    measurementId: 'G-Z271ETCSDL',
  );
}
